CRITICAL - 2021-05-31 22:44:05 --> Argument 1 passed to CodeIgniter\Database\BaseBuilder::join() must be of the type string, array given, called in D:\Allxampp\7.4\htdocs\vyaapar\app\Helpers\db_helper.php on line 15
#0 D:\Allxampp\7.4\htdocs\vyaapar\app\Helpers\db_helper.php(15): CodeIgniter\Database\BaseBuilder->join(Array)
#1 D:\Allxampp\7.4\htdocs\vyaapar\app\Controllers\admin\Admin.php(31): get_dbdata(Array)
#2 D:\Allxampp\7.4\htdocs\vyaapar\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\admin\Admin->index()
#3 D:\Allxampp\7.4\htdocs\vyaapar\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\admin\Admin))
#4 D:\Allxampp\7.4\htdocs\vyaapar\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 D:\Allxampp\7.4\htdocs\vyaapar\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-05-31 23:18:35 --> count(): Parameter must be an array or an object that implements Countable
#0 D:\Allxampp\7.4\htdocs\vyaapar\app\Helpers\db_helper.php(15): CodeIgniter\Debug\Exceptions->errorHandler(2, 'count(): Parame...', 'D:\\Allxampp\\7.4...', 15, Array)
#1 D:\Allxampp\7.4\htdocs\vyaapar\app\Controllers\admin\Admin.php(31): get_dbdata(Array)
#2 D:\Allxampp\7.4\htdocs\vyaapar\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\admin\Admin->index()
#3 D:\Allxampp\7.4\htdocs\vyaapar\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\admin\Admin))
#4 D:\Allxampp\7.4\htdocs\vyaapar\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 D:\Allxampp\7.4\htdocs\vyaapar\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-05-31 23:19:23 --> syntax error, unexpected '}', expecting end of file
#0 D:\Allxampp\7.4\htdocs\vyaapar\vendor\codeigniter4\framework\system\Controller.php(175): helper(Array)
#1 D:\Allxampp\7.4\htdocs\vyaapar\vendor\codeigniter4\framework\system\Controller.php(126): CodeIgniter\Controller->loadHelpers()
#2 D:\Allxampp\7.4\htdocs\vyaapar\app\Controllers\BaseController.php(37): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#3 D:\Allxampp\7.4\htdocs\vyaapar\vendor\codeigniter4\framework\system\CodeIgniter.php(891): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Allxampp\7.4\htdocs\vyaapar\vendor\codeigniter4\framework\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->createController()
#5 D:\Allxampp\7.4\htdocs\vyaapar\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 D:\Allxampp\7.4\htdocs\vyaapar\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-05-31 23:19:34 --> Undefined variable: key1
#0 D:\Allxampp\7.4\htdocs\vyaapar\app\Helpers\db_helper.php(16): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'D:\\Allxampp\\7.4...', 16, Array)
#1 D:\Allxampp\7.4\htdocs\vyaapar\app\Controllers\admin\Admin.php(31): get_dbdata(Array)
#2 D:\Allxampp\7.4\htdocs\vyaapar\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\admin\Admin->index()
#3 D:\Allxampp\7.4\htdocs\vyaapar\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\admin\Admin))
#4 D:\Allxampp\7.4\htdocs\vyaapar\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 D:\Allxampp\7.4\htdocs\vyaapar\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-05-31 23:37:33 --> extract() expects parameter 1 to be array, null given
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'extract() expec...', 'D:\\Allxampp\\7.4...', 60, Array)
#1 D:\Allxampp\7.4\htdocs\vyaapar\app\Helpers\db_helper.php(60): extract(NULL)
#2 D:\Allxampp\7.4\htdocs\vyaapar\app\Controllers\admin\Admin.php(31): get_dbdata(Array)
#3 D:\Allxampp\7.4\htdocs\vyaapar\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\admin\Admin->index()
#4 D:\Allxampp\7.4\htdocs\vyaapar\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\admin\Admin))
#5 D:\Allxampp\7.4\htdocs\vyaapar\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 D:\Allxampp\7.4\htdocs\vyaapar\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-05-31 23:37:56 --> Call to undefined method CodeIgniter\Database\MySQLi\Connection::join()
#0 D:\Allxampp\7.4\htdocs\vyaapar\app\Controllers\admin\Admin.php(31): get_dbdata(Array)
#1 D:\Allxampp\7.4\htdocs\vyaapar\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\admin\Admin->index()
#2 D:\Allxampp\7.4\htdocs\vyaapar\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\admin\Admin))
#3 D:\Allxampp\7.4\htdocs\vyaapar\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\Allxampp\7.4\htdocs\vyaapar\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
